### ISSUE TITLE
Gather all recent 3EA documents and see how it impacts our programs and research. 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#102]
* Gather all 3EA documents
* Highlight the different insights 
* see if / how it impacts our programs and research.

**Comment by sylvia-sable** [comment]
I will send my annotated pdfs this week.

**Comment by lauradereynal** [comment]
I'll liase with Kiruba to dive more into the content of the 3EA programs

**Comment by lauradereynal** [comment]
This is done. Closing it. we have good notes on the research results, now waiting for the program details.
