### ISSUE TITLE
Create CE and or Tunakujenga one pager

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#103]
@sylvia-sable can you create a 1 pager for CE and a 1 pager for Tunakujenga ? We need something super short that describes the programs well, and that we can share easily with everyone who needs a small reminder about the programs. Our design decks are too big for that. 

Can you make something for Thursday ?

**Comment by sylvia-sable** [comment]
@lauradereynal yes I can work on this for Thursday - I'll link this up with finalizing the pilot plans document.

**Comment by lauradereynal** [comment]
What's the status on the one pager?

**Comment by sylvia-sable** [comment]
@lauradereynal just sent for your review on email.
