### ISSUE TITLE
Finalize CE + TKJ Program roll out  doc 

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#115]

**Comment by lauradereynal** [comment]
What are these documents ? the decks? I closed the ticket on the CE one because I already finalized it for now. 

I think the next phase of these documents will be after the field visit: we will update them based on what we observed and what needs to change.

**Comment by sylvia-sable** [comment]
I want to finalize the program launch / roll out plans we used for CE and TKJ. This is different than design deck. I have a draft 1 but it needs to be updated with some changes I made while it was happening. I want to finish this before I go on leave @lauradereynal

**Comment by sylvia-sable** [comment]
What do you think @lauradereynal ?

**Comment by lauradereynal** [comment]
ok sounds good. I got confused with the "service design" mention. I'm changing the name to "program roll out".

**Comment by lauradereynal** [comment]
Hey @sylvia-sable can you send this to me asap please? I really need it this week. Marking as urgent. 
Bullet points will do, no need for anything pretty.

**Comment by sylvia-sable** [comment]
@lauradereynal this is complete as of yesterday. I updated the roll out plan with what we added and eliminated when actually implementing the written plan. You can find it here -https://docs.google.com/document/d/1oU_jmwSSQE3eih0YxLrWWRxqMolVLoy0OKNY-sz4hjk/edit# 

I made a comment at the end of the document that would be good to get your input on. I want to finalize this and archive in box. 

Thanks!
