### ISSUE TITLE
Write design brief for the church cinema 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#131]
Justina can prototype a new church cinema for Tunakujenga. Let's write a brief for her to follow while in the field. 
cc @sylvia-sable happy to leave this to you if you want to do it.

**Comment by sylvia-sable** [comment]
Sure I can take a crack at it while you're gone @lauradereynal

**Comment by lauradereynal** [comment]
Let's review it together and finalize the brief.

**Comment by lauradereynal** [comment]
https://docs.google.com/document/d/1v_5fNg9gRICM3pWfc3M17bG9EBAzw64BTUZLssdnGNo/edit doc here.

**Comment by lauradereynal** [comment]
I reviewed the doc, edited and scheduled time for us to talk it out tomorrow

**Comment by sylvia-sable** [comment]
@lauradereynal this is ready for your final input. One thought - why are we doing this for Tunakujenga and not for Coach Erevu? Dont' we expect the same out of Justina for both programs?
