### ISSUE TITLE
Write qualitative research plans for Justina's subsequent visits to the field

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#134]
#128

**Comment by lauradereynal** [comment]
work in progress here: https://docs.google.com/document/d/17pbhdThCybMEO68PFi1-50N5QwYUgNo2YpldVjDf9NM/edit#heading=h.96eardy51jse 

Let's review this with her on our call tomorrow. Can you edit directly in the doc ?

**Comment by lauradereynal** [comment]
I did a pass on that doc and wrote down thougths for the next few weeks.
