### ISSUE TITLE
Tunakujenga graduation prep + certificates

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#141]
@lauradereynal we have to think about what this entails. We saved the week of 4 February for a "graduation" and handing out of certificates. Based on what's happening in the field, what do you think we should do?

**Comment by lauradereynal** [comment]
Can you write a short plan for this and we will update justina ? Nothing special to note from our visit in the field. Let's just organize something nice. Either with everyone together or with individual churches. 
What's most important is the messaging we share during that moment. It will be people's final touch point about the program, and will be very important in terms of their experience. 
Here is what you should add to your plan: 
1. what to do for the certificates / ceremony
2. Who will say what 
3. How we want participants to feel and what we want them to remember
4. what is our message about next steps 
5. giving them a point of contact for the rest of the project 

and I'm probably forgetting something here.
