### ISSUE TITLE
Field logistics and check lists for september 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#18]
Just a giant todo for the country work in Tanzania 
- [x] planes x3 
- [x] accomodation in DAR 
- [x] visa
- [x] houses 
- [x] material for prototyping 
- [x] printer 
- [x] phones 
- [x] sim cards 
- [x] meetings with people
- [x] offering our time and our help 
- [x] shadowing plan 
- [x] driver 
- [x] cash for the incentives
- [x] cash advance for Laura and Shirley ?
- [x] snacks
- [x] camera 
- [x] polaroid 
- [x] usb sticks 
- [x] audio recording equipment ?

**Comment by lauradereynal** [comment]
@chilirodriguez do you have anything to add to this list of things to bring / make sure we have in Tanzania ?

**Comment by chilirodriguez** [comment]
- [x] SD cards 
- [x] power adapters?
- [x] hard drive 
- [x] a bunch of sticky notes 
- [x] tripod 
- [x] tablet?
