### ISSUE TITLE
Gather and read the learnings from Vroom 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#25]
Goal: locate the Vroom deck and data that were shared in the eudcation TU call, and make sure everyone has read it before we get to Tanzania. 

Responsible: @RDeitz01 do you think you could be responsible for obtaining the deck and sharing ?
People who need to read it: @chilirodriguez @pippayeats @jonthemac and myself

**Comment by RDeitz01** [comment]
Draft VROOM deck: https://docs.google.com/presentation/d/1r1moxXy51eRbov05U9TvnlXhj0dVfLrLv6fwQvxAHX0/edit#slide=id.g1e9381a015_0_15

**Comment by lauradereynal** [comment]
Thanks @RDeitz01

**Comment by lauradereynal** [comment]
all done
