### ISSUE TITLE
Sketch out the design identity work 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#29]
Write the list of questions that will let us understand people's identity and values.
Design the assets that we will use in the interviews. 

In collaboration with @chilirodriguez @pippayeats

**Comment by chilirodriguez** [comment]
You can see the list of questions and assets so far for the Spark prototype[ here](https://docs.google.com/document/d/1GCei-atc6yvWNiKK-O_9IkfvNth1QehpD5aF3ZNpSHI/edit?usp=sharing) I made this list for myself to make sense of what I need to make/have time to make.  I will make another doc with the same questions (and probably more) that we can print out when we do interviews. Please add in questions and comments @RDeitz01 @lauradereynal @pippayeats
