### ISSUE TITLE
learn the kind of games and songs that people do with children

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#30]
Goal: gather data about the type of games and songs that people do with their children, in order to inform the development of Graine

Questions: 
- What are some culturally appropriate body language or other demonstrations of affections ? 
- What is appropriate or not, to talk about with the kids?

**Comment by lauradereynal** [comment]
We learned a little bit, but not enough, and not systematic. 
This will need to be a research task for Paul, when there is time.

**Comment by lauradereynal** [comment]
@chilirodriguez you are leading on this task right ?

**Comment by chilirodriguez** [comment]
Yup. You can find the documents here:
[Game Collection](https://docs.google.com/presentation/d/1_BjV2NHTw1ohfBp7tzG96djrK5OtzlNz6g6jcoyPBrI/edit?usp=sharing)
[Story Collection](https://drive.google.com/open?id=1ZoajdPVSt4wd8m3YvuEZwTatrCnHhSAfRSUBfxiZHDk)
[Videos of Games](https://drive.google.com/open?id=1jX-LVAvEfGeeWZRwu5kzWOyIKrXWkiRU)
