### ISSUE TITLE
Develop a branding plan for each product 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#33]
develop a branding plan for each project.

**Comment by chilirodriguez** [comment]
I've added these into the Spark interview questions plans.  You can see it [here](https://docs.google.com/document/d/1GCei-atc6yvWNiKK-O_9IkfvNth1QehpD5aF3ZNpSHI/edit?usp=sharing), the boxes are in blue

**Comment by lauradereynal** [comment]
@chilirodriguez this can go on the list today
