### ISSUE TITLE
September trip deliverables 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#39]
# Priorities P1 

## Design research deliverables 
- [x] expand the personas work with relevant tech / incentives / media / motivations / literacy 
- [ ] put the personas on a deck 
- [x] Map the connections between the different actors of the project 
- [ ] User journeys for each concept with different time frames to understand how the product will play a role in their life. 
- [ ] Gender dynamics documented for each product 
- [ ] Draft branding work with ideas and next steps
- [ ] Stakeholder mapping for each of the concepts 
- [ ] Service Blueprints for each of the concepts

## Tech deliverables 
- [ ] Secure a dandelion account with unicef 
- [x] prototype (design, test, run live, feeback)  several flows for Graine 
- [x] prototype (design, test, run live, feeback)  several flows for Hekima  
- [x] prototype (design, test, run live, feeback)  several flows for Spark
- [ ] produce a tech feasibility report (by the Preakelt team) with detailed information about tech usage in Nyarugusu @jonthemac 
- [ ] includes tests that we will have performed to assess feasibility. 
- [ ] Whatsapp / chat social media  tested 
- [x] mobile web tested

## Concept testing / social business canvas 
- [x] Hekima: tested 2 different concepts. For example Hekima Coach / Hekima community to be revised after first week of itws
- [x] Graine: tested 2 different concepts. For example: Graine Cards / Graine Sms 
- [ ] Spark: tested 2 different concepts. TBD to work on with @chilirodriguez 
- [ ] Create a social business canvas for each concept

#  Nice to have P2 
- [x] recruitment methods for each product 
- [ ] Promotional methods 
- [ ] Incentives 
- [ ] cultural influences / effects on adoptions

**Comment by lauradereynal** [comment]
for reference, here is early gender work https://docs.google.com/spreadsheets/d/14Pld9Kj8D_drWhFHTUGJtwKcTOO_dVZYqIPDfWOO2t0/edit#gid=0

**Comment by chilirodriguez** [comment]
- { } Map

**Comment by lauradereynal** [comment]
@chilirodriguez @pippayeats @RDeitz01 there are things in this list that we did not quite touch. 

@pippayeats do you think it would be possible to have the tech feasibility report from Praekelt ?
