### ISSUE TITLE
Sprint #2 preparation for Graine

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#54]
**Goal**: prepare for Sprint # 2 taking place on November 20th to December 4th. 

**Design prep:**
- [x] write up prototyping plan 
- [ ] select final concept to move forward for testing 
- [ ] connect with someone in the field to prepare work - send them checklist 
- [ ] Decide what SEL material will be needed for this next sprint. 
- [x] create learning questions to drive our work 
- [ ] recruitment plan for the moms leaders
- [ ] recruitment plan for the moms participants 
- [ ] create video assets ? Script ? which competencies ? Which layout ? what is the video experience like ? what is the branding 
- [ ] create activity guide that follows the video being watched 
- [ ] early branding for club concept > family clubs or caregiver's clubs 
- [ ] pre-post evaluation questionnaires 
- [ ] social business canvas for selected concept 
- [x] personas documented with 2-3 portraits for each

**Logistics prep:**
- [ ] TOR revised 
- [ ] driver, budget, hr, visa, houses etc
- [ ] material translated 

@chilirodriguez let's complete this list and use it as a driver for the next couple weeks.

**Comment by chilirodriguez** [comment]
- { } Persona Deck

**Comment by lauradereynal** [comment]
## Caregiver clubs tied to their kids schools
- [ ] identify school to participate in test 
- [ ] identify club leader 
- [ ] train club leader (create training material)

**Comment by chilirodriguez** [comment]
Spark On-going Support?

- [ ] Find someone to keep check on the youth leaders
- [ ]  Self reporting 
- [ ] Child tracking sheets? 
- [ ] Mobisite update?

**Comment by lauradereynal** [comment]
What do you think we will need in terms of SEL content ? Can we cover that in our call tomorrow and circulate with Rena ? 
I'm adding a check box to that list.

**Comment by lauradereynal** [comment]
Sorry I did not mean to close this haha :D 
Feel free to paste links of your progress here if you have things you want me to look over.
