### ISSUE TITLE
Mid-Pilot synthesis - Share Plan for Feedback 

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#65]

**Comment by lauradereynal** [comment]
Just a note on this: It's important to take a moment and look at where we are, but we don't need a formal report and we don't need to take too much time writing an analysis we can publish. It's really about preparing January sprint, as opposed to publishing a mid-line. we dont have enough data for that.

**Comment by sylvia-sable** [comment]
@lauradereynal yes I got it. I think minimum we just want some internal documentation of our pivots / decision points. If we can share something with the team after our brainstorm that is a bonus, but not the driving objective of this.
