### ISSUE TITLE
Finalize Pilot Plans Document

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#76]
https://docs.google.com/document/d/1Emb7cgLzfzblkU15sVeRvOnIDxEMzLmnEBT_9uq1tGU/edit#heading=h.qkenttm4h8oj

**Comment by sylvia-sable** [comment]
@lauradereynal I took a pass at our document and commented where I need some input from you and Elizabeth. Can you review this week so that I can get this finalized? My hope is to link this up with our efforts to improve our Coach Erevu project page on the website, but obviously, it's most important and necessary to have this documented accurately all in one place as well.

**Comment by lauradereynal** [comment]
This is finally done 👍 😄

**Comment by sylvia-sable** [comment]
@lauradereynal this needs one more pass from you + to address my comments on the program implementation work. That section specifically needed to be cleaned up in order to be shared beyond our immediate team. Can you do this before end of week?

**Comment by lauradereynal** [comment]
done
