### ISSUE TITLE
Create Pilot 1-pager

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#77]

**Comment by lauradereynal** [comment]
Maybe this is the same doc than the 2 program one pager

1. CE Description 
2. CE pilot 
3. Tunak Description 
4. Tunak pilot 

what do you think ? the pilot description could be 3 lines for each.

**Comment by sylvia-sable** [comment]
@lauradereynal yes I think it is the same as your other ticket. I'm closing this one. I sent the 1-pager text for your input on email.
