### ISSUE TITLE
Write Ubongo / Tunakujenga Blog

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#78]

**Comment by lauradereynal** [comment]
Can you draft ~6 interview questions to Ubongo and share with Alex and I before we do the interview ?

**Comment by sylvia-sable** [comment]
@lauradereynal yes of course.

**Comment by lauradereynal** [comment]
let's wait until we have our pilot results and we can write a blog post to share our results.

**Comment by sylvia-sable** [comment]
@lauradereynal ready for your input - see email.
