### ISSUE TITLE
Tunakujenga M&E Database Analysis

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#82]

**Comment by lauradereynal** [comment]
This is 2 tasks: 
1. Visualization 
2. Analysis 

Who is doing the Visualization ?

**Comment by sylvia-sable** [comment]
@lauradereynal yes, this is 2 tasks. I want to assign analysis and visualization responsibilities on our call with elizabeth tomorrow for all of these mid-pilot synthesis tasks. thanks for catching this!
