### ISSUE TITLE
Prep scenario + stage gate materials for next week

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/dandelion#92]

**Comment by lauradereynal** [comment]
Let's coordinate on this one. Can we make a bullet point document, with answers to the SG questions + our own analysis.

**Comment by lauradereynal** [comment]
I'll take this forward for next week.

**Comment by sylvia-sable** [comment]
yes! @lauradereynal you are on stage gate questions. I will draft the scenarios, then we will combine.

**Comment by sylvia-sable** [comment]
@lauradereynal i updated you on email about this (sensitive docs were linked). Let me know what you think.

**Comment by lauradereynal** [comment]
Done and shared !
