### ISSUE TITLE
Write SOW for design support for our pilot work 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#96]
Write SOW for the design support needed in our pilot sprint.
related to #93

**Comment by lauradereynal** [comment]
Done !

**Comment by sylvia-sable** [comment]
@lauradereynal did you already do this? I want to use it to establish a contract etc. If not I can draft and have you review. Let me know.

**Comment by lauradereynal** [comment]
Done. It's something internal for staffing the whole portfolio, not good for making the SOW for Justina.
