### ISSUE TITLE
Make some light changes to the Tunakujenga and Coach Erevu programs for January 1st. 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/dandelion#98]
Brainstorm ideas to change the programs.

**Comment by lauradereynal** [comment]
Takeaways from our last week: 

- [ ] **Refresher kick off**: re boost programs and motivations for all stakeholders with a new kick off meeting+ framing for the leaders. Spend time making the FL and the AHM the best advocates for the programs –– **while not being blockers**. 
- [ ] **Schedule change:** find a way to change the meeting schedules so that they are easier to attend. 
- [ ] **Correct expectations on attendance and certificate**

**Comment by sylvia-sable** [comment]
@lauradereynal final chance to review the program tweaks plan [here](https://docs.google.com/document/d/1kbVURkPm0HdDqcBjUZ548plgLdBzBO8Voj_YRHsOjNg/edit#). Anything you want to add? I need to review this with Jacky and Sarah tomorrow.
